# git_test_reset2
今回のテストの内容完全に理解した
さっき1のbranchでミスったので作り直しています